server:
  port: 10010
logging:
  level:
    com.yuan: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsCorfigurations:
          ’[/**]’:
            al1owedOrigins: #允许哪些网站的跨域请求
              - "http://1ocalhost:8091"
            al1owedMethods: #允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            a11owedHeaders: “*” #允许在请求中携带的头信息
            a11owCredentia1s: true #是否允许携带
            cookiemaxAge: 360000 #这次跨域检测的有效期
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/teacher/**,  /parent/**, /student/**, /parStu/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: course-service
          uri: lb://courseservice
          predicates:
            - Path=/class/**, /course/**, /message/**, /stuMes/**, /subject/**
        - id: homework-service
          uri: lb://homeworkservice
          predicates:
            - Path=/homework/**, /picture/**, /stuHomework/**
        - id: review-service
          uri: lb://reviewservice
          predicates:
            - Path=/answer/**, /problem/**, /work/**