server:
  port: 8101
spring:
  datasource:
    url: jdbc:mysql://139.9.117.98:3306/bishe?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123@biShe
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.yuan: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

mybatis:
  type-aliases-package: com.yuan.homeworkservice.entity
  mapper-locations: classpath:mapper/*.xml

